### ISSUE TITLE
Review lessons page 

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/librarycarpentry.org#23]
Review lessons page: https://lc-new-website.netlify.app/lessons/

Content has been copied & pasted over from current lessons page except for the bottom section.  The current [LC lessons page](https://librarycarpentry.org/lessons/) includes information about lesson status definitions (alpha, beta, etc.), information about the lesson development process, and information on community lessons.  Should this information all be somewhere else and only directed to from here?

**Comment by tobyhodges** [comment]
This looks good to me, thanks @maneesha

**Comment by maneesha** [comment]
@tobyhodges Just to be sure, you want to keep the language about lesson stages etc. that does not appear anywhere on the other LP websites? I worry that it would be difficult to keep this information up to date and consistent.

**Comment by tobyhodges** [comment]
For now, yes. LC has taken a much more liberal approach to defining their curriculum, and the community governance is working towards establishing "lesson pathways" that will hopefully make all of this a bit more coherent in the near future. Regardless, it will certainly mean that the content and organisation of this lessons page will change soon.
