### ISSUE TITLE
Replace main picture on the site

### ISSUE THREAD

**Issue by OscarSiba** [LibraryCarpentry/librarycarpentry.org#38]
### What is the problem?

Due to the colour contrast considerations, please replace the current image on the LC new site with "pexels-yankrukov-8197496.jpg" from the [website images folder](https://drive.google.com/drive/folders/1Vz0H75cLMvx-pdmi57ZQDuip_fOb6S_A). 

### Location of problem (optional)

https://lc-new-website.netlify.app/

**Comment by maneesha** [comment]
@OscarSiba In the image you recommended, the faces are at the very top of the image and partially cut off.  When that gets rendered on the website, it captures the center of the image so you don't end up seeing faces at all.  Do you want to consider an image where the faces are more centered?  See preview here: https://deploy-preview-40--lc-new-website.netlify.app/

**Comment by OscarSiba** [comment]
Please use whichever image fits best between the images titled "centre-for-ageing-better-wkFRvw2lTAg-unsplash" OR "priscilla-du-preez-XkKCui44iM0-unsplash", both in the [website images folder](https://drive.google.com/drive/folders/1Vz0H75cLMvx-pdmi57ZQDuip_fOb6S_A).

**Comment by maneesha** [comment]
Addressed with #43
