### ISSUE TITLE
Style changes to LC website

### ISSUE THREAD

**Issue by OscarSiba** [LibraryCarpentry/librarycarpentry.org#41]
### How could the content be improved?

**About us**: https://lc-new-website.netlify.app/about-us/

- [x] Please also add the "Subscribe to our newsletter" button here. 
- [x]  On the third paragraph, please hyperlink "Since 2014" to this link: https://carp-new-website.netlify.app/about-us/#our-history

**Library Carpentry Lessons**: https://lc-new-website.netlify.app/lessons/

- [x] Please end all the sentences listed under "Our Core Objectives" with a full stop. 
- [x] The last sentence on that list ("Lesson materials are all available online...") should not be bulleted. It's a separate, standalone, sentence. 
- [x] Under "Core Curriculum", in the first paragraph, please spell instructor with a capital "I". 
- [x] Under "Retired Curriculum" please revise the second sentence to read: "They may include out-of-date..." 
- [x] Under the same section, please hyperlink reference to the [LC Curriculum Advisory Committee](https://lc-new-website.netlify.app/about-us/curriculum-advisors/). 
- [x] On the side bar please remove all these: 

![image](https://github.com/user-attachments/assets/ebe6e3b1-2584-41e4-bd30-4f80de0de8a3)

**Comment by maneesha** [comment]
Addressed with #42
