### ISSUE TITLE
Status of lc-python-intro

### ISSUE THREAD

**Issue by tobyhodges** [LibraryCarpentry/librarycarpentry.org#52]
@jt14den @chennesy what is the current status of the LC Python lesson? For example, [do you consider it stable enough to be safe to use in teaching demos](https://github.com/carpentries/instructor-training/issues/1682)? It is marked as `beta` on the lesson site, and looks pretty well fleshed out. But it is still listed as `alpha` on https://librarycarpentry.org/lessons/

Is the plan to update the lesson listing when the lesson pathways (#207) are merged?

**Comment by chennesy** [comment]
@tobyhodges Sorry I overlooked this message for so long! I'm working on a proposed update to the Lessons page right now that will include listing the Python lesson as beta. Hoping LC-CAC can review the updates to lessons.html in our Sept meeting, and get that page up to date before our larger conversation about pathways. 

To clarify, the current LC-CAC plan is to first update the lessons page with a series of minor improvements (without any pathways information) and then plan how to integrate/communicate pathways. 

Also, yes, I think LC-Python is stable enough to include as part of teaching demos. No major changes are planned at this stage. Just incremental improvements.

**Comment by jt14den** [comment]
@chennesy since we are meeting next in 2025, anything we can do to move this forward before then?

**Comment by chennesy** [comment]
@jt14den This PR should take care of it, once it is approved: https://github.com/LibraryCarpentry/librarycarpentry.org/pull/53

**Comment by maneesha** [comment]
@tobyhodges has been tagged for review.  Once he approves, I can merge.

**Comment by maneesha** [comment]
The comment above from @chennesy makes it seem that #53 takes care of this issue, but the comment in the PR says that it does not close this issue.  What else needs to be done?

**Comment by tobyhodges** [comment]
Let's go ahead and close this. I have delayed while trying to decide whether to list the lesson as available for teaching demos. I think I will leave it off the list for now: we typically only recommend for demos after the lesson has been marked stable.
